"""add photo faces

Revision ID: 383807d956ef
Revises: b0e6d06ec7c5
Create Date: 2026-10-07 01:13:44.889223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383807d956ef'
down_revision: Union[str, None] = 'b0e6d06ec7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_faces_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_faces')),
    sa.UniqueConstraint('face_id', name=op.f('uq_photo_faces_face_id'))
    )
    op.create_index(op.f('ix_photo_faces_photo_id'), 'photo_faces', ['photo_id'], unique=False)
    op.add_column('photos', sa.Column('face_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'face_status')
    op.drop_index(op.f('ix_photo_faces_photo_id'), table_name='photo_faces')
    op.drop_table('photo_faces')
    # ### end Alembic commands ###
